services:
  db_wallet:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./modules/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - default

  users:
    build: ./
    ports:
      - 30001:30001
    depends_on:
      - db_wallet
    networks:
      - skynet
      - default

networks:
  skynet:
    external: true
  default:
    external: false
